version: '3.0'

expectations:
  population_size: 1000

actions:
  
  generate_study_population:
    run: >
      cohortextractor:latest generate_cohort
        --study-definition study_definition
        --output-format=feather
    outputs:
      highly_sensitive:
        cohort: output/input.feather
        
  generate_study_population_monthly:
    run: >
      cohortextractor:latest generate_cohort
        --study-definition study_definition_monthly
        --output-format=feather
        --index-date-range "2021-01-01 to 2021-12-01 by month"
    outputs:
      highly_sensitive:
        cohort: output/input_monthly_*.feather
    
  generate_study_population_weekly:
    run: >
      cohortextractor:latest generate_cohort
        --study-definition study_definition_weekly
        --output-format=feather
        --index-date-range "2021-01-01 to 2021-12-24 by week" 
    outputs:
      highly_sensitive:
        cohort: output/input_weekly_*.feather

  generate_weekly_summary_table:
    run: python:latest python analysis/weekly_summary.py
    needs: [generate_study_population_weekly]
    outputs:
      moderately_sensitive:
        table: output/weekly_count.csv

  generate_study_counts_bp:
    run: >
      cohortextractor:latest generate_cohort
        --study-definition study_definition_counts_bp
        --output-format=feather
    outputs:
      highly_sensitive:
        cohort: output/input_counts_bp.feather

  generate_study_counts_eth:
    run: >
      cohortextractor:latest generate_cohort
        --study-definition study_definition_counts_eth
        --output-format=feather
    outputs:
      highly_sensitive:
        cohort: output/input_counts_eth.feather

  generate_study_counts_aaa:
    run: >
      cohortextractor:latest generate_cohort
        --study-definition study_definition_counts_aaa
        --output-format=feather
    outputs:
      highly_sensitive:
        cohort: output/input_counts_aaa.feather

  generate_top_5_table:
    run: python:latest python analysis/top_codes_table.py
    needs: [generate_study_counts_bp, generate_study_counts_aaa]
    outputs:
      moderately_sensitive:
        table: output/top_5_code_table_*.csv

  generate_codelist_report:
    run: >
      cohortextractor:latest generate_codelist_report
        --output-dir=output
        --codelist-path=codelists/opensafely-systolic-blood-pressure-qof.csv
        --start-date=2021-01-01
        --end-date=2021-12-31
    outputs:
      moderately_sensitive:
        table: output/counts_per_*.csv

  generate_measures:
    run: python:latest python analysis/generate_measures.py
    needs: [generate_codelist_report]
    outputs:
      moderately_sensitive:
        measure: output/measure_counts_per_week_practice.csv

  generate_deciles_charts:
    run: >
      deciles-charts:v0.0.15
        --input-files output/measure_counts_per_week_practice.csv
        --output-dir output
    config:
      show_outer_percentiles: false
      tables:
        output: true
      charts:
        output: true
    needs: [generate_measures]
    outputs:
      moderately_sensitive:
        deciles_charts: output/deciles_*_*.*