version: '3.0'

expectations:
  population_size: 1000

actions:
  
  generate_codelist_report:
    run: >
      cohortextractor:latest generate_codelist_report
        --output-dir=output
        --codelist-path=codelists/opensafely-systolic-blood-pressure-qof.csv
        --start-date=2021-01-01
        --end-date=2021-12-31
    outputs:
      moderately_sensitive:
        table: output/counts_per_*.csv
        list_sizes: output/list_sizes.csv

  generate_measures:
    run: python:latest python analysis/generate_measures.py
    needs: [generate_codelist_report]
    outputs:
      moderately_sensitive:
        measure: output/measure_counts_per_week_per_practice.csv

  generate_top_5_table:
    run: python:latest python analysis/top_codes_table.py

    outputs:
      moderately_sensitive:
        table: output/top_5_code_table_*.csv

  generate_deciles_charts:
    run: >
      deciles-charts:v0.0.15
        --input-files output/measure_counts_per_week_per_practice.csv
        --output-dir output
    config:
      show_outer_percentiles: false
      tables:
        output: true
      charts:
        output: true
    needs: [generate_measures]
    outputs:
      moderately_sensitive:
        deciles_charts: output/deciles_*_*.*