version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population:
    run: >
      cohortextractor:latest generate_cohort
        --study-definition study_definition
        --output-format=feather
    outputs:
      highly_sensitive:
        cohort: output/input.feather
        
  generate_study_population_monthly:
    run: >
      cohortextractor:latest generate_cohort
        --study-definition study_definition_monthly
        --output-format=feather
        --index-date-range "2021-01-01 to 2021-12-01 by month"
    outputs:
      highly_sensitive:
        cohort: output/input_monthly_*.feather
    

  generate_study_population_weekly:
    run: >
      cohortextractor:latest generate_cohort
        --study-definition study_definition_weekly
        --output-format=feather
        --index-date-range "2021-01-01 to 2021-12-24 by week" 
    outputs:
      highly_sensitive:
        cohort: output/input_weekly_*.feather
    

  generate_study_counts_bp:
    run: >
      cohortextractor:latest generate_cohort
        --study-definition study_definition_counts_bp
        --output-format=feather
    outputs:
      highly_sensitive:
        cohort: output/input_counts_bp.feather

  generate_study_counts_eth:
    run: >
      cohortextractor:latest generate_cohort
        --study-definition study_definition_counts_eth
        --output-format=feather
    outputs:
      highly_sensitive:
        cohort: output/input_counts_eth.feather

  generate_study_counts_aaa:
    run: >
      cohortextractor:latest generate_cohort
        --study-definition study_definition_counts_aaa
        --output-format=feather
    outputs:
      highly_sensitive:
        cohort: output/input_counts_aaa.feather

  generate_top_5_table:
    run: python:latest python analysis/top_codes_table.py
    needs: [generate_study_counts_bp, generate_study_counts_eth, generate_study_counts_aaa]
    outputs:
      moderately_sensitive:
        table: output/top_5_code_table_*.csv
