version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv
  generate_study_counts:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_counts
    outputs:
      highly_sensitive:
        cohort: output/input_counts.csv
